tdlist/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("remove_task/<task_id>", views.remove_task, name="remove_task"),
]

todolist/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tdlist.urls')),
    path('vetportal/', include('vet_portal.urls')),
]
if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vet_portal/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.vet_index, name="vet_index"),
    path("signup", views.signup, name="signup"),
    path("basic", views.basic, name="basic"),
    path("login", views.user_login, name="login"),
    path("update", views.update_profile, name="update"),
    path("findbook/<pk>", views.findbook, name="findbook"),
    path("doctor/<d_id>/<c_id>", views.doctor, name="doctor"),
    path("appointment/<pk>/<d_id>", views.appointment, name="appointment"),
    path("remove_patient/<pk>", views.remove_patient, name="remove_patient"),
    path("slip/<pk>", views.slip, name="slip"),
    path("logout", views.user_logout, name="user_logout"),
]

vet_portal/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_profile')
    profile_pic = models.ImageField(upload_to='user/images/profiles', default='user/images/profiles/profile_picture.png',
                                null=True)
    mobile = models.CharField(max_length=10)
    address = models.CharField(max_length=50)
    state = models.CharField(max_length=500)
    city = models.CharField(max_length=50)
    zip = models.CharField(max_length=6)

    def __str__(self):
        return self.user.first_name


class Doctor(models.Model):
    name = models.CharField(max_length=20)
    mobile = models.CharField(max_length=10)
    email = models.CharField(max_length=30)
    experience = models.IntegerField()
    price = models.CharField(max_length=10, default=0)
    about = models.CharField(max_length=50)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=30)
    qualification = models.CharField(max_length=50)
    profile = models.ImageField(upload_to='vet_portal/images/others', default='user/images/profiles/profile_picture.png',
                                null=True)

    def __str__(self):
        return self.name


class Patient(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='patients')
    name = models.CharField(max_length=20)
    age = models.IntegerField()
    profile = models.ImageField(upload_to='user/images/profiles', default='user/images/profiles/profile_picture.png',
                                null=True)

    def __str__(self):
        return self.name


class Appointment(models.Model):
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, related_name='doctor')
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name='appointments')
    date = models.DateTimeField()
    reason = models.CharField(max_length=100)

    def __str__(self):
        return self.doctor.name + '-' + self.patient.name

vet_portal/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile, Patient, Appointment
from django.db.models import Q
from django.contrib.auth import authenticate


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('profile_pic', 'mobile', 'address', 'city', 'state', 'zip')
        widgets = {
            'mobile': forms.TextInput(attrs={'class': 'form-control'}),
            'address': forms.TextInput(attrs={'class': 'form-control'}),
            'city': forms.TextInput(attrs={'class': 'form-control'}),
            'state': forms.TextInput(attrs={'class': 'form-control'}),
            'zip': forms.TextInput(attrs={'class': 'form-control'})
        }


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password')
        widgets = {
            'password': forms.PasswordInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control'})
        }


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control'})
        }


class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    def clean(self):
        username_text = self.cleaned_data['username']
        password = self.cleaned_data['password']

        user_name = User.objects.filter(Q(username=username_text)).first()
        if user_name:
            username = user_name.username
        else:
            raise forms.ValidationError("No user with this username or mobile.")
        user = authenticate(username=username, password=password)
        if not user:
            raise forms.ValidationError("Username/password is incorrect")


class PatientForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = {'name', 'age', 'profile', 'user'}
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'age': forms.NumberInput(attrs={'class': 'form-control'}),
            'user': forms.TextInput(attrs={'hidden': 'hidden'}),
        }


class AppointmentForm(forms.ModelForm):
    class Meta:
        model = Appointment
        fields = {'date', 'reason', 'patient', 'doctor'}
        widgets = {
            'date': forms.DateTimeInput(attrs={'class': 'form-control', 'type': 'datetime-local'}),
            'reason': forms.TextInput(attrs={'class': 'form-control'}),
            'patient': forms.TextInput(attrs={'hidden': 'hidden'}),
            'doctor': forms.TextInput(attrs={'hidden': 'hidden'}),
        }

vet_portal/views.py
from django.shortcuts import render, redirect
from .forms import ProfileForm, UserForm, LoginForm, PatientForm, AppointmentForm, UserUpdateForm
from django.contrib.auth.models import User
from django.db.models import Q
from django.contrib.auth import login, logout
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Doctor, Patient, Appointment

# Create your views here.


def vet_index(request):
    patients = Patient.objects.filter(user=request.user)
    initial = {'user': request.user}
    form = PatientForm(initial=initial)
    if request.method == 'POST':
        form = PatientForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('vet_index'))
        else:
            print(form.errors)
    context = {
        'patients': patients,
        'form': form,
    }
    return render(request, 'vetportal/vet_index.html', context)


def signup(request):
    p_form = ProfileForm()
    u_form = UserForm()
    if request.method == 'POST':
        p_form = ProfileForm(request.POST, request.FILES)
        u_form = UserForm(request.POST)
        if p_form.is_valid() and u_form.is_valid():
            user = u_form.save(commit=False)
            password = u_form.cleaned_data['password']
            user.set_password(password)
            user.save()
            profile = p_form.save(commit=False)
            profile.user = user
            profile.save()

            return HttpResponseRedirect(reverse('login'))
    context = {
        'p_form': p_form,
        'u_form': u_form,
    }

    return render(request, 'vetportal/signup.html', context)


def basic(request):
    return render(request, 'vetportal/basic.html')


def user_login(request):
    form = LoginForm()
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            user = User.objects.filter(Q(username=username)).first()
            login(request, user)
            return HttpResponseRedirect(reverse('vet_index'))
    context = {
        'form': form,
    }
    return render(request, 'vetportal/login.html', context)


def update_profile(request):
    user = request.user
    try:
        p_form = ProfileForm(instance=user.user_profile)
    except:
        p_form = ProfileForm()
    u_form = UserUpdateForm(instance=user)
    if request.method == 'POST':
        try:
            p_form = ProfileForm(request.POST, request.FILES, instance=user.user_profile)
        except:
            p_form = ProfileForm(request.POST, request.FILES)

        u_form = UserUpdateForm(request.POST, instance=user)
        if p_form.is_valid() and u_form.is_valid():
            user = u_form.save(commit=False)
            user.save()
            p_form.save()

            return HttpResponseRedirect(reverse('vet_index'))
    context = {
        'p_form': p_form,
        'u_form': u_form,
    }
    return render(request, 'vetportal/update.html', context)


def findbook(request, pk):
    doctors = Doctor.objects.all()
    all_doctors = Doctor.objects.all()
    searched_doctor = request.GET.get('doctor')
    city = request.GET.get('city')
    if searched_doctor:
        doctors = doctors.filter(name=searched_doctor)
        print(searched_doctor)
    if city:
        doctors = doctors.filter(city=city)

    context = {
        'doctors': doctors,
        'pk': pk,
        'all_doctors': all_doctors,
        'searched_doctor': searched_doctor,
        'city': city,
    }
    return render(request, 'vetportal/findbook.html', context)


def doctor(request, d_id, c_id):
    d_details = Doctor.objects.get(id=d_id)
    context = {
        'd_details': d_details,
        'c_id': c_id,
        'd_id': d_id,
    }
    return render(request, 'vetportal/doctorDetails.html', context)


def appointment(request, pk, d_id):
    patient = Patient.objects.get(id=pk)
    initial = {'patient': patient, 'doctor': d_id}
    form = AppointmentForm(initial=initial)
    if request.method == 'POST':
        form = AppointmentForm(request.POST)
        if form.is_valid():
            new_appointment = form.save()
            return HttpResponseRedirect(reverse('slip', args=(new_appointment.pk,)))
        else:
            print(form.errors)
    context = {
        'patient': patient,
        'form': form,
    }
    return render(request, 'vetportal/appointment.html', context)


def remove_patient(request, pk):
    Patient.objects.filter(pk=pk).delete()
    return HttpResponseRedirect(reverse('vet_index'))


def slip(request, pk):
    app_query =Appointment.objects.get(id=pk)
    context = {
        'app_query': app_query
    }
    return render(request, 'vetportal/slip.html', context)


def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('login'))

templates/vetportal/profile-popover.html
<a href="{% url 'update' %}" class="btn btn-primary">Update Profile</a><a href="{% url 'user_logout' %}" class="btn btn-primary">Logout</a>

templates/vetportal/signup.html
<!doctype html>
<html lang="en">
  <head>
      {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/vetportal_css.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.3/css/fontawesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <title>Signup</title>
    <style>

.profile-pic-div{
        height: 100px;
        width: 100px;
        position: absolute;
        border: 1px solid rgb(167, 167, 167);
        border-radius: 50%;
        overflow: hidden;
      
    }
    #photo{
        height: 100%;
        width: 100%;
    }
    #file{
        display: none;

    }
    #uploadBtn{
        height: 40px;
        width: 100%;
       transition: ease 0.5s;
        transform: translate(39px, -35px);
        font-size: 24px;
        
    }

    </style>
  
</head>
  <body>
    <div class="container">
      <div class="row" id="row" style="padding-top: 50px;">
          <div class="main-body mx-auto p-0" id="main-body" style="width: 400px;">

            <!--navbar-->
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">
                    <button class="toggle-btn mx-2" id="toggle-btn" type="button"><b>
                        <span class="navbar-toggler-icon" style="color: rgb(179, 179, 179);"></span>
                    </b></button>
                    
                  <a class="navbar-brand" href="#"><img src="{% static 'images/pupten.png' %}"></a>
                  <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  </div>
                </div>
            </nav>

           <!--Rest Contents-->
           <div class="main-content m-0" id="main-content">
               

            <form class="row" method="post" enctype="multipart/form-data" style="min-height: 300px; padding: 10px;" >
                {% csrf_token %}
                <h4>Enter your details :</h4>
                <div class="row">
                    
                    <div class="col-md-7 col-8 m-0">
                        <div class=>
                            <label for="inputFirst_Name4" class="form-label">First Name</label>
                            {{ u_form.first_name }}
                            <span class="text-danger"><h6>{{ u_form.first_nam.errors.as_text }}</h6></span>
                        </div>
                          <div>
                            <label for="inputPassword4" class="form-label">Last Name</label>
                            {{ u_form.last_name }}
                            <span class="text-danger"><h6>{{ u_form.last_name.errors.as_text }}</h6></span>
                          </div>
                    </div>

                    <div class="col-md-5 col-4 profile_section">  
                       
                      <div class="profile-pic-div">
                        <img src='{%  static "images\profile_picture.png" %}' id="photo" name="profile_pic">
                         <spna style="display: none;">{{ p_form.profile_pic }}</spna>
                        
                          <span class="text-danger">{{ p_form.profile_pic.errors.as_text }}</span>
                        <label for="id_profile_pic" id="uploadBtn"><i class="fas fa-camera"></i></label>
                      </div>
                    </div>
                </div>
                <div class="col-md-6">
                  <label for="inputPassword4" class="form-label">Username</label>
                  {{ u_form.username }}
                  <span class="text-danger"><h6>{{ u_form.username.errors.as_text }}</h6></span>
                </div>
                <div class="col-md-6">
                  <label for="inputPassword4" class="form-label">Email</label>
                  {{ u_form.email }}
                    <span class="text-danger"><h6>{{ u_form.email.errors.as_text }}</h6></span>
                </div>
                <div class="col-md-6 m-0">
                  <label for="inputCity" class="form-label">Password</label>
                  {{ u_form.password }}
                    <span class="text-danger"><h6>{{ u_form.password.errors.as_text }}</h6></span>
                </div>
                <div class="col-md-6 m-0">
                  <label for="inputCity" class="form-label">Mobile</label>
                  {{ p_form.mobile }}
                  <span class="text-danger"><h6>{{ p_form.mobile.errors.as_text }}</h6></span>
                </div>
                <div class="col-12 m-0">
                  <label for="inputAddress" class="form-label">Address</label>
                  {{ p_form.address }}
                  <span class="text-danger"><h6>{{ p_form.address.errors.as_text }}</h6></span>
                </div>
                <div class="col-md-5 m-0">
                  <label for="inputCity" class="form-label">City</label>
                  {{ p_form.city }}
                  <span class="text-danger"><h6>{{ p_form.city.errors.as_text }}</h6></span>
                </div>
                <div class="col-md-4 m-0">
                  <label for="inputState" class="form-label">State</label>
                  {{ p_form.state }}
                  <span class="text-danger"><h6>{{ p_form.state.errors.as_text }}</h6></span>
                </div>
                <div class="col-md-3 m-0">
                  <label for="inputZip" class="form-label">Zip</label>
                  {{ p_form.zip }}
                  <span class="text-danger"><h6>{{ p_form.zip.errors.as_text }}</h6></span>
                </div>
               
                <div class="col-3">
                    <span class="text-danger"></span>
                  <button type="submit" class="mt-2 mb-1 signup-submit" id="signup-submit" name="signup-submit">Sign up</button>
                </div>
                <h6>Already have an account ? <b><a href="{% url 'login' %}" style="text-decoration: none;">Login</a></b> here</h6>
              </form>

           </div>

          </div>
      </div>
  </div>  
  <script
    src="https://code.jquery.com/jquery-3.6.0.js"
    integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
    crossorigin="anonymous"></script>
    
    
    <script>
        $(document).ready(function(){
            $('#toggle-btn').click(function(){
                document.getElementById('toggle-btn').style.border = "3px solid rgb(98, 166, 255)"
            });
        });
    </script>
    
    <script>
       
        const imgDiv = document.querySelector('.profile-pic-div');
 const img = document.querySelector('#photo');
 const file = document.querySelector('#id_profile');
 const uploadBtn = document.querySelector('#uploadBtn');
 
 
 
 imgDiv.addEventListener('mouseenter', function(){
     uploadBtn.style.display = "block";
 });
 

 
 imgDiv.addEventListener('mouseleave', function(){
     uploadBtn.style.display = "none";
 });
 
 
 
 file.addEventListener('change', function(){
    
     const choosedFile = this.files[0];
 
     if (choosedFile) {
 
         const reader = new FileReader(); 
 
         reader.addEventListener('load', function(){
             img.setAttribute('src', reader.result);
         });
 
         reader.readAsDataURL(choosedFile);
 
         
     }
 });
 
 
 
     </script>
 

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    
  </body>
</html>

templates/vetportal/update.html
<!doctype html>
<html lang="en">
  <head>
      {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/vetportal_css.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.3/css/fontawesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <title>Update</title>
    <style>

.profile-pic-div{
        height: 100px;
        width: 100px;
        position: absolute;
        border: 1px solid rgb(167, 167, 167);
        border-radius: 50%;
        overflow: hidden;
      
    }
    #photo{
        height: 100%;
        width: 100%;
    }
    #file{
        display: none;

    }
    #uploadBtn{
        height: 40px;
        width: 100%;
       transition: ease 0.5s;
        transform: translate(39px, -35px);
        font-size: 24px;
        
    }

    </style>
  
</head>
  <body>
    <div class="container">
      <div class="row" id="row" style="padding-top: 50px;">
          <div class="main-body mx-auto p-0" id="main-body" style="width: 400px;">

            <!--navbar-->
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">
                    <button class="toggle-btn mx-2" id="toggle-btn" type="button"><b>
                        <span class="navbar-toggler-icon" style="color: rgb(179, 179, 179);"></span>
                    </b></button>
                    
                  <a class="navbar-brand" href="#"><img src="{% static 'images/pupten.png' %}"></a>
                  <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  </div>
                </div>
            </nav>

           <!--Rest Contents-->
           <div class="main-content m-0" id="main-content">
               

            <form class="row" method="post" enctype="multipart/form-data" style="min-height: 300px; padding: 10px;" >
                {% csrf_token %}
                <h5>Update Your Profile :</h5>
                <div class="row">
                    
                    <div class="col-md-7 col-8 m-0">
                        <div class=>
                            <label for="inputFirst_Name4" class="form-label">First Name</label>
                            {{ u_form.first_name }}
                            <span class="text-danger"><h6>{{ u_form.first_nam.errors.as_text }}</h6></span>
                        </div>
                          <div>
                            <label for="inputPassword4" class="form-label">Last Name</label>
                            {{ u_form.last_name }}
                            <span class="text-danger"><h6>{{ u_form.last_name.errors.as_text }}</h6></span>
                          </div>
                    </div>

                    <div class="col-md-5 col-4 profile_section">  
                       
                      <div class="profile-pic-div">
                        <img src='{%  static "images\profile_picture.png" %}' id="photo" name="profile_pic">
                         <spna style="display: none;">{{ p_form.profile_pic }}</spna>
                        
                          <span class="text-danger">{{ p_form.profile_pic.errors.as_text }}</span>
                        <label for="id_profile_pic" id="uploadBtn"><i class="fas fa-camera"></i></label>
                      </div>
                    </div>
                </div>
                <div class="col-md-6">
                  <label for="inputPassword4" class="form-label">Username</label>
                  {{ u_form.username }}
                  <span class="text-danger"><h6>{{ u_form.username.errors.as_text }}</h6></span>
                </div>
                <div class="col-md-6">
                  <label for="inputPassword4" class="form-label">Email</label>
                  {{ u_form.email }}
                    <span class="text-danger"><h6>{{ u_form.email.errors.as_text }}</h6></span>
                </div>
                <div class="col-md-6 m-0">
                  <label for="inputCity" class="form-label">Mobile</label>
                  {{ p_form.mobile }}
                  <span class="text-danger"><h6>{{ p_form.mobile.errors.as_text }}</h6></span>
                </div>
                <div class="col-12 m-0">
                  <label for="inputAddress" class="form-label">Address</label>
                  {{ p_form.address }}
                  <span class="text-danger"><h6>{{ p_form.address.errors.as_text }}</h6></span>
                </div>
                <div class="col-md-5 m-0">
                  <label for="inputCity" class="form-label">City</label>
                  {{ p_form.city }}
                  <span class="text-danger"><h6>{{ p_form.city.errors.as_text }}</h6></span>
                </div>
                <div class="col-md-4 m-0">
                  <label for="inputState" class="form-label">State</label>
                  {{ p_form.state }}
                  <span class="text-danger"><h6>{{ p_form.state.errors.as_text }}</h6></span>
                </div>
                <div class="col-md-3 m-0">
                  <label for="inputZip" class="form-label">Zip</label>
                  {{ p_form.zip }}
                  <span class="text-danger"><h6>{{ p_form.zip.errors.as_text }}</h6></span>
                </div>
               
                <div class="col-3">
                    <span class="text-danger"></span>
                  <button type="submit" class="mt-2 mb-1 signup-submit" id="signup-submit" name="signup-submit">Update</button>

           </div>

          </div>
      </div>
  </div>  
  <script
    src="https://code.jquery.com/jquery-3.6.0.js"
    integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
    crossorigin="anonymous"></script>
    
    
    <script>
        $(document).ready(function(){
            $('#toggle-btn').click(function(){
                document.getElementById('toggle-btn').style.border = "3px solid rgb(98, 166, 255)"
            });
        });
    </script>
    
    <script>
       
        const imgDiv = document.querySelector('.profile-pic-div');
 const img = document.querySelector('#photo');
 const file = document.querySelector('#id_profile_pic');
 const uploadBtn = document.querySelector('#uploadBtn');
 
 //if user hover on img div 
 
 imgDiv.addEventListener('mouseenter', function(){
     uploadBtn.style.display = "block";
 });
 
 //if we hover out from img div
 
 imgDiv.addEventListener('mouseleave', function(){
     uploadBtn.style.display = "none";
 });
 
 //lets work for image showing functionality when we choose an image to upload
 
 //when we choose a foto to upload
 
 file.addEventListener('change', function(){
     //this refers to file
     const choosedFile = this.files[0];
 
     if (choosedFile) {
 
         const reader = new FileReader(); //FileReader is a predefined function of JS
 
         reader.addEventListener('load', function(){
             img.setAttribute('src', reader.result);
         });
 
         reader.readAsDataURL(choosedFile);
 
         
     }
 });
 
 
 
     </script>
 

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    
  </body>
</html>