tdlist/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("remove_task/<task_id>", views.remove_task, name="remove_task"),
]

todolist/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tdlist.urls')),
    path('vetportal/', include('vet_portal.urls')),
]
if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tdlist/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class todoList(models.Model):
    title = models.CharField(default="", max_length=20)
    start_date = models.DateField()
    update = models.DateField(auto_now=True)
    com_date = models.DateField()
    content = models.TextField(default="")
    is_completed = models.BooleanField(default=False)

    def __str__(self):
        return self.title

templates/index.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap" rel="stylesheet">
    <title>To Do List</title>
  </head>
  <body style="background: url('./static/images/bg.jpg');width: 100%;height: 100%;">
    <div class="container">

        <div class="row" style="padding-top: 25px;">

           <!--To do List-->

            <div class="header mb-5" id="main-div">
                <h2 class="mb-2">To Do List !!</h2>
                <div class="switch text-end mx-2 my-1" id="switch">
                    <a href="{% url 'signup' %}">Vet-Portal</a>
                    <a id="switch-btn" onclick=""  {% if blink %} class="blink" {% else %} class="abc" {% endif %} style="text-decoration: none;">Upcoming</a>
                </div>

                <div class="todo-list p-0 m-0">
                    <form method="post">
                        {% csrf_token %}
                       <!-- <h5 style="color: white;">TITLE</h5>  -->
                    <div class="todo-heading mb-3" id="todo-heading">
<!--                        <input type="text" placeholder="Title.." id="title" class="table-input" name="title">-->
                        {{ form.title }}
                        {{ form.title.errors.as_text }}
                    </div>
                    <div class="todo-content p-0 m-0" id="todo-content" style="display: none;">
                        <div class="main-content-div" id="main-content-div">
                            <div class="create-content p-0 m-0" id="create-content">
                                <div class="m-1">
                                    <label>Start Date : </label><br>
<!--                                    <input type="date" name="startDate" id="startDate" class="table-input">-->
                                    {{ form.start_date }}
                                    {{ form.start_date.errors.as_text }}
                                </div>
                                <div class="mb-2 mx-1">
                                    <label>Completion Date : </label><br>
<!--                                    <input type="date" name="comDate"  id="comDate" class="table-input">-->
                                    {{ form.com_date }}
                                    {{ form.com_date.errors.as_text }}
                                </div>
                                <section>
                                    <h5 style="color: rgb(30, 221, 255);"><b>Content</b></h5>
                                    {{ form.content }}
                                    {{ form.content.errors.as_text }}
<!--                                    <textarea name="todoText" id="todoText" cols="40" rows="10" placeholder="Content..." class="table-input"></textarea>-->
                                </section>
                            </div>
                        </div>
                          <div class="addDiv">
                            <input class="addBtn" id="addBtn" type="submit" value="Add" name="task-submit">
                          </div>
                    </div>
                    </form>
                </div>


            </div>

            <!--Remainder-->

            <div class="header-rem mb-5" id="main-div-rem" style="display: none;">
                <h2 class="mb-2">UpComings !!</h2>
                <div class="date-time text-end mx-1" id="date-time">
                   <label>Date : </label> <span id="date"></span><br>
                    <label>Time  : </label><span id="time"></span>
                </div>
                <div class="switch2 text-end mx-2 my-1" id="switch2">
                    <a onclick="">To do List</a>
                </div>

                <div class="todo-list-rem p-0 m-0">
                   <table border="1" class="created-list table table-dark table-striped" id="created-list-rem">
                       <tbody>
                            {% for i in upcoming_list %}
                            <tr>
                                <th>{{ i.title }}</th>
                                <th>{{ i.start_date }}</th>
                                <th>{{ i.com_date }}</th>
                                <th>{{ i.content|truncatechars:20 }}</th>
                                <th><a href="{% url 'remove_task' task_id=i.pk %}">Remove</a></th>
                            </tr>
                            {% empty %}
                            <h3 style="color: green;">No upcoming Events</h3>
                            {% endfor %}
                       </tbody>
                   </table>
                </div>


            </div>

        </div>

        <table border="1" class="created-list table table-dark table-striped" id="created-list" {% if not tdlist %}style="display:none;"{% endif %}>
            <thead>
              <tr>
                <th>Status</th>
                <th>Title</th>
                <th>Start Date</th>
                <th>Completion Date</th>
                <th>Content</th>
                <th>Action</th>
              </tr>

            </thead>
            <tbody>
                {% for i in tdlist %}
                <tr>
                    <th>
                        <form method="post" class="completed-form">
                            {% csrf_token %}
                        <input type="hidden" value="{{ i.pk }}" name="task-id">
                        {% if i.is_completed %}
                        <input type="checkbox" value="1" checked name="completed" class="completed">
                        {% else %}
                        <input type="checkbox" value="1" name="completed" class="completed">
                        {% endif %}
                        </form>
                    </th>
                    <th>{{ i.title }}</th>
                    <th>{{ i.start_date }}</th>
                    <th>{{ i.com_date }}</th>
                    <th>{{ i.content }}</th>
                    <th><a href="{% url 'remove_task' task_id=i.pk %}">Remove</a></th>
                </tr>
                {% endfor %}
            </tbody>
        </table>

    </div>

    </div>


    <script
    src="https://code.jquery.com/jquery-3.6.0.js"
    integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
    crossorigin="anonymous"></script>
<script>
  $(document).ready(function(){

    console.log($(".hidden-row").html())

    // Showing form on key down

    $("#id_title").keydown(function(){
      if($(this).val() == ""){
      $("#todo-content").slideUp(1200);
      }
      else{
        $("#todo-content").slideDown(1200);
      }
    })

    // Adding row in table on click

    $("#addBtn").click(function(){
       document.getElementById('created-list').style.display = "inline-table"
        var row = $(".hidden-row:first").clone(true)
        $(".table-input").each(function(){
            var attr_id = $(this).attr("id")
            $(row).find("[data-id="+attr_id+"]").text($(this).val())
            $(this).val("")
        })
        $(".created-list").find("tbody").append(row)
    })

    // Removing row on click

    $(document).on("click", ".remove-row", function(){
        $(this).parent().parent().remove()
    })

    // Complete form

    $(".completed").change(function(){
    $(this).parent().submit();
    })

  });
</script>


<script>
 $(document).ready(function(){
     $("#switch").click(function(){
        document.getElementById('created-list').style.display = "none"
         $("#main-div").fadeOut(1000);
         setTimeout( "$('#main-div-rem').fadeIn(1000);",1000);
     })

     $('#switch2').click(function(){
        setTimeout( "document.getElementById('created-list').style.display = 'inline-table';",1000);
        setTimeout( '$("#main-div").fadeIn(1000);',1000);
         $('#main-div-rem').fadeOut(1000);
     })

 })
</script>


<script>
    let a;
    let time;
    setInterval(() => {
      a = new Date();
      time = a.getHours() + ':' + a.getMinutes() + ':' + a.getSeconds();
      document.getElementById('time').innerHTML = time;}, 1000);


</script>
<script>
    let today = new Date().toLocaleDateString()
    document.getElementById('date').innerHTML = today;
</script>





    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
  </body>
</html>